### ISSUE TITLE
fatal error in observation framework

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#20]
I've finally managed to get the test runner to run to completion with the new content. Running the observation framework on this results in a fatal error like the following.

Processed to frame 1410...
Processed to frame 1420...
Processed to frame 1430...
Processed to frame 1440...
Processed to frame 1450...
INFO     Entering log file: logs/82514e1c-c2df-11eb-8700-0242ac110002.log
ERROR    Serious error is detected, when analysing ['C0007.MP4']! '1e2d4e896d043cf27da46181032a012a': Traceback (most recent call last):
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/configuration_parser.py", line 69, in parse_tests_json
    test_path = self.tests_json["tests"][test_id]["path"]
KeyError: '1e2d4e896d043cf27da46181032a012a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "observation_framework.py", line 228, in main
    run(input_video_files, log_manager, global_configurations)
  File "observation_framework.py", line 105, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 403, in iter_qr_codes_in_video
    self._process_pre_test_qr_code(new_pre_test_qr_code)
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 312, in _process_pre_test_qr_code
    self._load_new_test()
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 197, in _load_new_test
    self.test_path, test_code = self.configuration_parser.parse_tests_json(
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/configuration_parser.py", line 76, in parse_tests_json
    raise Exception(e)
Exception: '1e2d4e896d043cf27da46181032a012a'
Traceback (most recent call last):
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/configuration_parser.py", line 69, in parse_tests_json
    test_path = self.tests_json["tests"][test_id]["path"]
KeyError: '1e2d4e896d043cf27da46181032a012a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "observation_framework.py", line 228, in main
    run(input_video_files, log_manager, global_configurations)
  File "observation_framework.py", line 105, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 403, in iter_qr_codes_in_video
    self._process_pre_test_qr_code(new_pre_test_qr_code)
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 312, in _process_pre_test_qr_code
    self._load_new_test()
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 197, in _load_new_test
    self.test_path, test_code = self.configuration_parser.parse_tests_json(
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/configuration_parser.py", line 76, in parse_tests_json
    raise Exception(e)
Exception: '1e2d4e896d043cf27da46181032a012a'
INFO     Device Observation Framework has finished analysing all selected recordings, Device Observation Framework is exiting.

**Comment by yanj-github** [comment]
Hi @jpiesing  can you check your test runner "tests.json" file "http://127.0.0.1:8000/tests.json" see if you can see "1e2d4e896d043cf27da46181032a012a" please?

You should see something like:
"1e2d4e896d043cf27da46181032a012a": {
            "path": <xxx/xxx.html>,
            "video": <video path>,
            "audio": <audio path>,
            "code": <test code>,
            "config": <further config>
... ...
        },

**Comment by jpiesing** [comment]
> Hi @jpiesing can you check your test runner "tests.json" file "http://127.0.0.1:8000/tests.json" see if you can see "1e2d4e896d043cf27da46181032a012a" please?
> 
> You should see something like:
> "1e2d4e896d043cf27da46181032a012a": {
> "path": <xxx/xxx.html>,
> "video":

@yanj-github Nothing with that key.

**Comment by yanj-github** [comment]
OF is looking up hex code "1e2d4e896d043cf27da46181032a012a" in tests.json file to get information such as test code and its configuration. If it is not found the error is raised. 
I guess you were trying old recordings with updated test runner. Or maybe something went not right when generating the test. 
tests.json gets updated on test generation process.

**Comment by jpiesing** [comment]
I've just done a brand new recording with the same results. Here's the tests.json file.

[tests.json.zip](https://github.com/cta-wave/device-observation-framework/files/6577693/tests.json.zip)

Processed to frame 1410...
Processed to frame 1420...
Processed to frame 1430...
Processed to frame 1440...
Processed to frame 1450...
INFO     Entering log file: logs/82514e1c-c2df-11eb-8700-0242ac110002.log
ERROR    Serious error is detected, when analysing ['C0007.MP4']! '1e2d4e896d043cf27da46181032a012a': Traceback (most recent call last):
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/configuration_parser.py", line 69, in parse_tests_json
    test_path = self.tests_json["tests"][test_id]["path"]
KeyError: '1e2d4e896d043cf27da46181032a012a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "observation_framework.py", line 228, in main
    run(input_video_files, log_manager, global_configurations)
  File "observation_framework.py", line 105, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 403, in iter_qr_codes_in_video
    self._process_pre_test_qr_code(new_pre_test_qr_code)
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 312, in _process_pre_test_qr_code
    self._load_new_test()
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 197, in _load_new_test
    self.test_path, test_code = self.configuration_parser.parse_tests_json(
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/configuration_parser.py", line 76, in parse_tests_json
    raise Exception(e)
Exception: '1e2d4e896d043cf27da46181032a012a'
Traceback (most recent call last):
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/configuration_parser.py", line 69, in parse_tests_json
    test_path = self.tests_json["tests"][test_id]["path"]
KeyError: '1e2d4e896d043cf27da46181032a012a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "observation_framework.py", line 228, in main
    run(input_video_files, log_manager, global_configurations)
  File "observation_framework.py", line 105, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 403, in iter_qr_codes_in_video
    self._process_pre_test_qr_code(new_pre_test_qr_code)
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 312, in _process_pre_test_qr_code
    self._load_new_test()
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/observation_framework_processor.py", line 197, in _load_new_test
    self.test_path, test_code = self.configuration_parser.parse_tests_json(
  File "/home/jon/TV_Standards/CTA/wave/dpctf-test-deployment/device-observation-framework/configuration_parser.py", line 76, in parse_tests_json
    raise Exception(e)
Exception: '1e2d4e896d043cf27da46181032a012a'
INFO     Device Observation Framework has finished analysing all selected recordings, Device Observation Framework is exiting.

**Comment by yanj-github** [comment]
Thanks @jpiesing I cannot see "1e2d4e896d043cf27da46181032a012a" from your tests.json file. Can you post a screen shot of the pre-test screen where it is saying "next test is about to start" from your recording please?

**Comment by louaybassbouss** [comment]
> @louaybassbouss
> The tests.json file has no hex code "1e2d4e896d043cf27da46181032a012a" but the running test shows "test_id":"1e2d4e896d043cf27da46181032a012a" can you help to dignose the issue here please?

@yanj-github  we will investigate this today and come back to you.

**Comment by louaybassbouss** [comment]
> > @louaybassbouss
> > The tests.json file has no hex code "1e2d4e896d043cf27da46181032a012a" but the running test shows "test_id":"1e2d4e896d043cf27da46181032a012a" can you help to dignose the issue here please?
> 
> @yanj-github we will investigate this today and come back to you.

@yanj-github after investigation we identified the reason for the bug and we are working on a hotfix (tomorrow during the day).

**Comment by louaybassbouss** [comment]
> > > @louaybassbouss
> > > The tests.json file has no hex code "1e2d4e896d043cf27da46181032a012a" but the running test shows "test_id":"1e2d4e896d043cf27da46181032a012a" can you help to dignose the issue here please?
> > 
> > 
> > @yanj-github we will investigate this today and come back to you.
> 
> @yanj-github after investigation we identified the reason for the bug and we are working on a hotfix (tomorrow during the day).

@yanj-github the bug should be fixed now can you check please. make sure when you create the new docker image to use `./build.sh master latest --reload-tests --reload-runner` 
@jpiesing the filenames are now as you requested in one of the closed issues e.g. [avc_15_30_60-online/sequential-track-playback__t1.html](https://github.com/cta-wave/dpctf-tests/blob/master/generated/avc_15_30_60-online/sequential-track-playback__t1.html) there is no repetition of `avc_15_30_60` in the filepath/filename. @yanj-github maybe this is also important for you to consider.

**Comment by jpiesing** [comment]
Fixed.
