### ISSUE TITLE
OF exiting: list index out of range

### ISSUE THREAD

**Issue by FritzHeiden** [cta-wave/device-observation-framework#47]
Some recordings I am analysing with the OF eventually result in the same error: `IndexError: list index out of range` 

I will share a recording with you via email.

config.ini:
```ini
[GENERAL]
test_runner_url = <our_hosted_instance>
sort_input_files_by = filename
log_file_path = logs
result_file_path = results
session_log_threshold = 100
missing_frame_threshold = 0
consecutive_no_qr_threshold = 0
end_of_session_timeout = 10
no_qr_code_timeout = 5
search_qr_area_to = 60
qr_area_margin = 50
duplicated_qr_check_count = 3

[TOLERANCES]
start_frame_num_tolerance = 0
end_frame_num_tolerance = 0
mid_frame_num_tolerance = 10
splice_start_frame_num_tolerance = 0
splice_end_frame_num_tolerance = 0
```

Logs:
```console
INFO     Start a New test: cfhd_12.5_25_50-local/sequential-track-playback__t10.html
ERROR    Serious error is detected, when analysing ['input.mp4']! list index out of range: Traceback (most recent call last):
  File "observation_framework.py", line 516, in main
    do_adaptive_threshold_scan,
  File "observation_framework.py", line 378, in run
    vidcap, starting_camera_frame_number, qr_code_areas
  File "/home/me/device-observation-framework/observation_framework_processor.py", line 636, in iter_qr_codes_in_video
    self._process_test_status_qr_code(new_test_status_qr_code)
  File "/home/me/device-observation-framework/observation_framework_processor.py", line 364, in _process_test_status_qr_code
    self._make_observations()
  File "/home/me/device-observation-framework/observation_framework_processor.py", line 287, in _make_observations
    self.time_diff_file,
  File "/home/me/device-observation-framework/test_code/sequential_track_playback.py", line 169, in make_observations
    frame_rate = mezzanine_qr_codes[-1].frame_rate
IndexError: list index out of range
Traceback (most recent call last):
  File "observation_framework.py", line 516, in main
    do_adaptive_threshold_scan,
  File "observation_framework.py", line 378, in run
    vidcap, starting_camera_frame_number, qr_code_areas
  File "/home/me/device-observation-framework/observation_framework_processor.py", line 636, in iter_qr_codes_in_video
    self._process_test_status_qr_code(new_test_status_qr_code)
  File "/home/me/device-observation-framework/observation_framework_processor.py", line 364, in _process_test_status_qr_code
    self._make_observations()
  File "/home/me/device-observation-framework/observation_framework_processor.py", line 287, in _make_observations
    self.time_diff_file,
  File "/home/me/device-observation-framework/test_code/sequential_track_playback.py", line 169, in make_observations
    frame_rate = mezzanine_qr_codes[-1].frame_rate
IndexError: list index out of range
INFO     Device Observation Framework has finished analysing all selected recordings, Device Observation Framework is exiting.
```

**Comment by yanj-github** [comment]
@FritzHeiden I cannot see same error for test cfhd_12.5_25_50-local/sequential-track-playback__t10.html
Can you double check the recording shared on email is the right one please?

**Comment by yanj-github** [comment]
I have commited fixes for this issue.

**Comment by FritzHeiden** [comment]
Thank you, I reran analysis on affected recordings and everything worked fine
