### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by FritzHeiden** [cta-wave/device-observation-framework#63]
Performing analysis of new recordings I ran into the error described in #47 again.

```
INFO     Making observation [OF] Every sample S[k,s] shall be rendered and the samples shall be rendered in increasing presentation time order....
INFO     Making observation [OF] The playback duration of the playback matches the duration of the CMAF Track, i.e. TR [k, S] = TR [k, 1] + td[k]....
INFO     Making observation [OF] The start-up delay should be sufficiently low, i.e., TR [k, 1] - Ti < TSMax....
INFO     Making observation [OF] The presented sample matches the one reported by the currentTime value within the tolerance of the sample duration....
ERROR    Serious error is detected, when analysing ['/usr/app/recordings/20231006_084000_philips.mp4']! list index out of range: Traceback (most recent call last):
  File "observation_framework.py", line 516, in main
    run(
  File "observation_framework.py", line 377, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/usr/app/device-observation-framework/observation_framework_processor.py", line 636, in iter_qr_codes_in_video
    self._process_test_status_qr_code(new_test_status_qr_code)
  File "/usr/app/device-observation-framework/observation_framework_processor.py", line 364, in _process_test_status_qr_code
    self._make_observations()
  File "/usr/app/device-observation-framework/observation_framework_processor.py", line 284, in _make_observations
    results = self.test_class.make_observations(
  File "/usr/app/device-observation-framework/test_code/sequential_track_playback.py", line 187, in make_observations
    result = observation_class.make_observation(
  File "/usr/app/device-observation-framework/observations/sample_matches_current_time.py", line 244, in make_observation
    if change_type_list[change_count - 1] == "splicing":
IndexError: list index out of range
Traceback (most recent call last):
  File "observation_framework.py", line 516, in main
    run(
  File "observation_framework.py", line 377, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/usr/app/device-observation-framework/observation_framework_processor.py", line 636, in iter_qr_codes_in_video
    self._process_test_status_qr_code(new_test_status_qr_code)
  File "/usr/app/device-observation-framework/observation_framework_processor.py", line 364, in _process_test_status_qr_code
    self._make_observations()
  File "/usr/app/device-observation-framework/observation_framework_processor.py", line 284, in _make_observations
    results = self.test_class.make_observations(
  File "/usr/app/device-observation-framework/test_code/sequential_track_playback.py", line 187, in make_observations
    result = observation_class.make_observation(
  File "/usr/app/device-observation-framework/observations/sample_matches_current_time.py", line 244, in make_observation
    if change_type_list[change_count - 1] == "splicing":
IndexError: list index out of range
INFO     Device Observation Framework has finished analysing all selected recordings, Device Observation Framework is
exiting.
```

**Comment by yanj-github** [comment]
@FritzHeiden Thanks for reporting the issue, can you let me know which test this is please? And if this test has a correct playout paramer please?

**Comment by FritzHeiden** [comment]
The test is `playback-over-wave-baseline-splice-constraints__splice_main_splice_ad.html` and it has a correct playout parameter. I will try to get an anonymized version of the recording to you

**Comment by yanj-github** [comment]
Thanks @FritzHeiden for the information I will have a look and it would be great if you can pass the recording please?
I am unable to replicate same error.

**Comment by jpiesing** [comment]
October 24th meeting
@louaybassbouss to email the contacts at the manufacturer of the device concerned telling them that it is necessary to share the recording with Resillion to reproduce an error, that Resillion confirm the confidentiality of the recording will be respected and giving them (say) 5 days to object.

**Comment by jpiesing** [comment]
I confirm this is reproducible. I get the following result running the OF against the recording on my laptop.

DEBUG    Frame Number=250 updating Last appear Frame=30280
DEBUG    Frame Number=250 updating Last appear Frame=30281
DEBUG    Status=finished Last Action=pause Current Time=15.76 Delay=26 Captured on Frame=30281
INFO     Making observation [OF] Every sample S[k,s] shall be rendered and the samples shall be rendered in increasing presentation time order....
DEBUG    [FAIL]:  Last frame found is 250, expected to end at 288. Last frame number tolerance is 0. Number of changes does not match the 'playout' configuration. Test is configured to change 3 times. Actual number of change is 5.  Total of missing frames is 38.
INFO     Making observation [OF] The playback duration of the playback matches the duration of the CMAF Track, i.e. TR [k, S] = TR [k, 1] + td[k]....
DEBUG    [PASS] Playback duration is 15754.09ms, expected track duration is 15760.0ms. Allowed tolerance is 40ms and duration frame tolerance is 0. Starting missing frame number is 0. Ending missing frame number is 38.
INFO     Making observation [OF] The start-up delay should be sufficiently low, i.e., TR [k, 1] - Ti < TSMax....
DEBUG    [PASS] Maximum permitted startup delay is 1000ms.The presentation start up delay is 271.208ms
INFO     Making observation [OF] The presented sample matches the one reported by the currentTime value within the tolerance of the sample duration....
ERROR    Serious error is detected, when analysing ['../20231006_084000_philips.mp4']! list index out of range: Traceback (most recent call last):
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework.py", line 516, in main
    run(
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework.py", line 377, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework_processor.py", line 636, in iter_qr_codes_in_video
    self._process_test_status_qr_code(new_test_status_qr_code)
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework_processor.py", line 364, in _process_test_status_qr_code
    self._make_observations()
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework_processor.py", line 284, in _make_observations
    results = self.test_class.make_observations(
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/test_code/sequential_track_playback.py", line 187, in make_observations
    result = observation_class.make_observation(
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observations/sample_matches_current_time.py", line 244, in make_observation
    if change_type_list[change_count - 1] == "splicing":
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework.py", line 516, in main
    run(
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework.py", line 377, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework_processor.py", line 636, in iter_qr_codes_in_video
    self._process_test_status_qr_code(new_test_status_qr_code)
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework_processor.py", line 364, in _process_test_status_qr_code
    self._make_observations()
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observation_framework_processor.py", line 284, in _make_observations
    results = self.test_class.make_observations(
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/test_code/sequential_track_playback.py", line 187, in make_observations
    result = observation_class.make_observation(
  File "/home/jon/TV_Standards/CTA/wave/wave-device-tf/observation-framework/device-observation-framework/observations/sample_matches_current_time.py", line 244, in make_observation
    if change_type_list[change_count - 1] == "splicing":
IndexError: list index out of range
INFO     Device Observation Framework has finished analysing all selected recordings, Device Observation Framework is exiting.

**Comment by yanj-github** [comment]
Thanks @FritzHeiden and @jpiesing I will have a look.

**Comment by yanj-github** [comment]
This is now fixed on main please have a look.

**Comment by jpiesing** [comment]
> This is now fixed on main please have a look.

I ran the main branch last night on the same recording and it ran to completion.

@FritzHeiden If you're OK with this, please close the issue.

**Comment by FritzHeiden** [comment]
> > This is now fixed on main please have a look.
> 
> I ran the main branch last night on the same recording and it ran to completion.
> 
> @FritzHeiden If you're OK with this, please close the issue.

Sounds good, closing
