### ISSUE TITLE
ERROR    Serious error is detected! index 0 is out of bounds for axis 0 with size 0:

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-observation-framework#92]
I got this error running the OF on the Philips TV recording from the Berlin plugfest on a PC with more memory than my laptop.
It didn't happen on my laptop. If cannot be reproduced on another PC then we can close the issue unless/until someone else finds it.

Processed to frame 4780...
DEBUG    Status=finished Last Action=pause Current Time=29.999999 Delay=19 Captured on Frame=4785
/home/jon/.local/lib/python3.10/site-packages/numpy/fft/_pocketfft.py:94: RuntimeWarning: invalid value encountered in fft
  return ufunc(a, fct, axes=[(axis,), (), (axis,)], out=out)
ERROR    Serious error is detected! index 0 is out of bounds for axis 0 with size 0: Traceback (most recent call last):
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework.py", line 591, in main
    run(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework.py", line 445, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework_processor.py", line 754, in iter_qr_codes_in_video
    self._process_test_status_qr_code(new_test_status_qr_code)
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework_processor.py", line 527, in _process_test_status_qr_code
    self._make_observations()
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework_processor.py", line 441, in _make_observations
    results = self.test_class.make_observations(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/test_code/sequential_track_playback.py", line 369, in make_observations
    audio_segments = self._get_audio_segments(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/test_code/sequential_track_playback.py", line 306, in _get_audio_segments
    offset, audio_segments = decode_audio_segments(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/dpctf_audio_decoder.py", line 247, in decode_audio_segments
    trimmed_data, offset = trim_audio(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/dpctf_audio_decoder.py", line 202, in trim_audio
    trim_from = get_trim_from(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/dpctf_audio_decoder.py", line 94, in get_trim_from
    offset1 = get_time_from_segment(subject_data, segment_data_1)
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/audio_file_reader.py", line 90, in get_time_from_segment
    result = result_tuple[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework.py", line 591, in main
    run(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework.py", line 445, in run
    last_camera_frame_number = observation_framework.iter_qr_codes_in_video(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework_processor.py", line 754, in iter_qr_codes_in_video
    self._process_test_status_qr_code(new_test_status_qr_code)
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework_processor.py", line 527, in _process_test_status_qr_code
    self._make_observations()
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/observation_framework_processor.py", line 441, in _make_observations
    results = self.test_class.make_observations(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/test_code/sequential_track_playback.py", line 369, in make_observations
    audio_segments = self._get_audio_segments(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/test_code/sequential_track_playback.py", line 306, in _get_audio_segments
    offset, audio_segments = decode_audio_segments(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/dpctf_audio_decoder.py", line 247, in decode_audio_segments
    trimmed_data, offset = trim_audio(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/dpctf_audio_decoder.py", line 202, in trim_audio
    trim_from = get_trim_from(
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/dpctf_audio_decoder.py", line 94, in get_trim_from
    offset1 = get_time_from_segment(subject_data, segment_data_1)
  File "/media/jon/c14de6c5-19b4-4aa3-8603-5342d9d4d9ae/work/of/device-observation-framework/audio_file_reader.py", line 90, in get_time_from_segment
    result = result_tuple[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by yanj-github** [comment]
@jpiesing I’ve been unable to replicate the issue on my end. The results should not be empty, as we have a check in place to ensure the audio recording data is not empty before processing. One potential cause might be related to the version of the NumPy package in use. Could you confirm which version of NumPy is currently installed on your PC? This will help us rule out any compatibility issues.

**Comment by yanj-github** [comment]
@jpiesing I think I know where is the issue I will fix this.

**Comment by jpiesing** [comment]
I've confirmed that this error is resolved & that the PC concerned can now successfully run the OF.
